name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Install Apko
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -Lo apko https://github.com/chainguard-dev/apko/releases/latest/download/apko-linux-amd64
        chmod +x apko
        sudo mv apko /usr/local/bin/

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Apko Image
      run: |
        make run-image



